# Generated by Django 3.0.2 on 2020-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='due_date',
            field=models.DateField(default='2020-02-09'),
        ),
    ]
